<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>checkbox_rememberMe</name>
   <tag></tag>
   <elementGuidId>cf94722f-f922-45ec-b610-5871acb88cac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#inputCheckbox</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inputCheckbox']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>96cc6786-a40a-473f-81e8-07ffd3f4809c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>14f94f2d-652a-45b5-b669-41a4dd055bb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputCheckbox</value>
      <webElementGuid>05bc3187-c78b-46e5-af9e-1ff59287ebf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>rememberMe</value>
      <webElementGuid>35e7c6df-0751-41d2-aae2-217d3e308883</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inputCheckbox&quot;)</value>
      <webElementGuid>3895bb91-e93d-4993-b664-c1b8e0da190a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inputCheckbox']</value>
      <webElementGuid>eef500c7-51b1-4ea1-91c3-ada85c4cc245</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div/div/div/form/div/div/div[3]/input</value>
      <webElementGuid>a8bce172-630a-4daf-8256-e2dc574ab50b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>dce26542-545c-4861-96e3-d7069a7ee3b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'inputCheckbox' and @name = 'rememberMe']</value>
      <webElementGuid>c2e7d838-fe05-412f-8694-320008789733</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
