<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_role_Senior</name>
   <tag></tag>
   <elementGuidId>69225b71-9164-424f-9982-ce328b5a6262</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inputrolesenior']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#inputrolesenior</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3fe29384-849d-4504-b574-49239103f267</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>login-input-role </value>
      <webElementGuid>6946c767-501e-4504-9590-76e970c8df2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputrolesenior</value>
      <webElementGuid>367628eb-85a6-4559-b6d2-c323397a3b8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>role</value>
      <webElementGuid>98ff605f-7f62-46fa-94f8-4baaa29099ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>c9841b92-561b-48fa-8dbb-4b94301d3df8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Senior</value>
      <webElementGuid>424a313a-ef78-444e-90cf-2a458dcf77bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inputrolesenior&quot;)</value>
      <webElementGuid>82d0ce80-7ccc-403f-be33-b2b4b471fed5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inputrolesenior']</value>
      <webElementGuid>c1544c9b-9804-4af4-9d7f-514aff78441d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div/div/div/form/div/div[5]/div/div/input</value>
      <webElementGuid>936dd3cd-de96-4755-81b2-3655d13c952f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/input</value>
      <webElementGuid>8c733c6d-cc95-48dc-afd4-2ed7adecc928</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'inputrolesenior' and @name = 'role' and @type = 'radio']</value>
      <webElementGuid>57056e05-c127-4aa6-b13f-7bac42f9be13</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
