<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input_First_Last_Name</name>
   <tag></tag>
   <elementGuidId>641263c5-c54b-44ed-9c5f-13b87df45509</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#inputname</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inputname']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>db134235-92c9-474d-bad6-0d1c70816516</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>login-input </value>
      <webElementGuid>fadcc1af-0d88-4d10-889b-391779b7e77f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputname</value>
      <webElementGuid>a9a4ddd1-90be-4860-ba72-a5ba2106b935</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>18bbc59b-335c-43a7-a16a-e68009e0aeb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>name</value>
      <webElementGuid>481c9ac6-6c2a-4ff4-ba06-6b1f9bd5a142</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Example: Mark Johnson</value>
      <webElementGuid>2f416d69-82b0-426e-a9e6-43d7432d252d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inputname&quot;)</value>
      <webElementGuid>43912448-7eb2-4e9c-8a5f-ed91b9791d65</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inputname']</value>
      <webElementGuid>45408110-db5d-4dfa-883b-14a675427f1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div/div/div/form/div/div/input</value>
      <webElementGuid>33580591-0b04-40c2-be69-8aef75c6ad15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>911a124a-b551-40f7-9a38-f0092323791f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'inputname' and @type = 'text' and @name = 'name' and @placeholder = 'Example: Mark Johnson']</value>
      <webElementGuid>ac115276-fd4c-4a30-93fb-877e634ba711</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
