<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input_ZIP_code</name>
   <tag></tag>
   <elementGuidId>8f32062a-ea48-4ef5-9e90-833487fc63cd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#inputzipcode</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inputzipcode']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6d14997a-c276-4949-a48e-9ae77fe135ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>login-input </value>
      <webElementGuid>7c11f726-8e0e-4a52-b783-62cb16c6e837</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputzipcode</value>
      <webElementGuid>c61fc05f-01da-49fb-b074-c198931b9ac1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>45c5e2c0-4841-414d-93ed-63e5aa4fca27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>zipcode</value>
      <webElementGuid>42bc3794-d502-494b-9c35-9df06e3650d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter ZIP code of your location</value>
      <webElementGuid>4e5f4fad-3e8f-4fbd-b4b0-4d44039127f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inputzipcode&quot;)</value>
      <webElementGuid>a9e99993-8434-46e9-bfb0-a45bcbb12814</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inputzipcode']</value>
      <webElementGuid>82838afd-d19b-45b9-84ff-78d9213c7118</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div/div/div/form/div/div[2]/input</value>
      <webElementGuid>db93ddd4-1eac-4906-9956-2e874eda7a2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>4c1fbc72-6396-4daa-86fa-9b54b3aefcb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'inputzipcode' and @type = 'text' and @name = 'zipcode' and @placeholder = 'Enter ZIP code of your location']</value>
      <webElementGuid>93c1ca95-c122-4e87-af0c-d56aea8ea8f7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
