<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_h1_Thank you</name>
   <tag></tag>
   <elementGuidId>03721b11-2dd4-4fbf-8e4f-7ee280879fd2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/h1</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h1.heading.h1.text-center.heading-thankyou</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>a471cedd-1bb6-48ff-8e2f-321698e709a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>heading h1 text-center heading-thankyou</value>
      <webElementGuid>530b3b26-7942-451a-90de-591719d17888</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Thank you!</value>
      <webElementGuid>b8227ece-e382-4d65-8dfc-0b79f9779fe9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App&quot;]/div[@class=&quot;body-side--container wrapper&quot;]/div[@class=&quot;mx-auto thankyou-container&quot;]/h1[@class=&quot;heading h1 text-center heading-thankyou&quot;]</value>
      <webElementGuid>8e6cc8e3-8e08-476e-8f7f-2bba76938e46</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/h1</value>
      <webElementGuid>1ceb9466-feba-4281-a9eb-aa2891572a60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capture object:'])[1]/preceding::h1[2]</value>
      <webElementGuid>e970076d-7a60-44ee-a008-1eced40a95ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alt'])[1]/preceding::h1[2]</value>
      <webElementGuid>d394a0da-1f22-465b-8661-b209dbdc8ac2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Thank you!']/parent::*</value>
      <webElementGuid>fb8f1fad-167f-4855-add6-096e3812f40d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>616386a7-65bf-4083-aac9-ca2cc9056cd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'Thank you!' or . = 'Thank you!')]</value>
      <webElementGuid>c3ea9542-854d-4a0a-ba83-b98623490397</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
