<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_h1_Educational_Background</name>
   <tag></tag>
   <elementGuidId>125ff8de-6ce2-49a7-81bd-f766179a1d53</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/form/div/div/div/div/div/h1</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h1.heading.h3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>68fdc4ea-991c-4ccf-8e8b-383e47479e97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>heading h3</value>
      <webElementGuid>6557d11f-c1b3-4309-83f7-c25989b1d41d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1. Educational and Professional Background</value>
      <webElementGuid>83b57ea6-547b-4661-8f07-8093199f316e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App&quot;]/div[@class=&quot;body-side--container inner-wrapper&quot;]/div[@class=&quot;px-2&quot;]/form[1]/div[@class=&quot;row justify-content-between p-0&quot;]/div[@class=&quot;p-0&quot;]/div[@class=&quot;col-12 p-0 my-3 border border-secondary-subtle shadow-sm rounded-bottom&quot;]/div[@class=&quot;row m-0 border border-bottom-secondary-subtle&quot;]/div[@class=&quot;col-11 p-2&quot;]/h1[@class=&quot;heading h3&quot;]</value>
      <webElementGuid>745ffeb8-4add-44b3-8554-6f331e82f49d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/form/div/div/div/div/div/h1</value>
      <webElementGuid>86efb0c8-a897-4ed2-89c4-0cf12869fd69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please feel free to edit as appropriate.'])[1]/following::h1[1]</value>
      <webElementGuid>7be21a38-c0b1-4c14-a76f-d07882a5b1a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Palak'])[1]/following::h1[2]</value>
      <webElementGuid>bb81b1b3-546f-45da-b914-4b0588c3fc4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Re-record'])[1]/preceding::h1[4]</value>
      <webElementGuid>b24ae057-1a94-404c-bfcb-9a316b3b95d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save &amp; Continue'])[1]/preceding::h1[4]</value>
      <webElementGuid>aa72efb8-6fc5-4431-8b08-e9565744c349</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='1. Educational and Professional Background']/parent::*</value>
      <webElementGuid>fd48e8fa-9450-4476-9d83-73468a70579f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div/div/div/h1</value>
      <webElementGuid>7b0d17fc-0838-4aa4-9d43-863329c74a84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = '1. Educational and Professional Background' or . = '1. Educational and Professional Background')]</value>
      <webElementGuid>303442a6-64d9-4403-bc54-66cca9612086</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
