<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Senior_typing</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>fb53f473-3ef6-4a80-8edb-2863f8baa092</testSuiteGuid>
   <testCaseLink>
      <guid>e9d14981-7784-45bc-842b-a47c056c87c8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Senior_TestCases/Senior_createProfile_Type</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>50c3456f-b3e4-4c3c-b2b1-1b9013af47b5</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Senior_Data</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>50c3456f-b3e4-4c3c-b2b1-1b9013af47b5</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>UserName</value>
         <variableId>8ddf70dd-d54c-486d-9e6d-bed3b9349256</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>50c3456f-b3e4-4c3c-b2b1-1b9013af47b5</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Role</value>
         <variableId>f9646872-0227-4fc3-a00d-5e1048c2bf3c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>50c3456f-b3e4-4c3c-b2b1-1b9013af47b5</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Email</value>
         <variableId>c053c35d-10ef-4a13-90c4-a45ee2a85b84</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>50c3456f-b3e4-4c3c-b2b1-1b9013af47b5</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Profile</value>
         <variableId>d7a05443-a7ab-4dbb-b1b8-d6fabb6c2da4</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
